package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

func newInitCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init <name>",
		Short: "Scaffold a new context repo structure",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			name := args[0]

			if err := os.MkdirAll(name, 0o755); err != nil {
				return fmt.Errorf("creating directory: %w", err)
			}

			// index.md
			indexContent := fmt.Sprintf("# %s\n\nThis directory contains agent-optimized documentation generated by [distill](https://github.com/dotbrains/distill).\n\nLoad subdirectory indexes to see available documents.\n", name)
			if err := os.WriteFile(filepath.Join(name, "index.md"), []byte(indexContent), 0o644); err != nil {
				return err
			}

			// .gitignore
			gitignore := ".distill-state.yaml\n"
			if err := os.WriteFile(filepath.Join(name, ".gitignore"), []byte(gitignore), 0o644); err != nil {
				return err
			}

			// README.md
			readme := fmt.Sprintf("# %s\n\nAgent-optimized documentation generated by [distill](https://github.com/dotbrains/distill).\n\nClone into `~/.claude/docs/` (or wherever your agents read context from) to make this available to AI agents.\n\n## Setup\n\n```sh\ncd ~/.claude\ngit clone <this-repo-url> docs\n```\n\n## Updating\n\n```sh\ncd ~/.claude/docs\ngit pull\n```\n", name)
			if err := os.WriteFile(filepath.Join(name, "README.md"), []byte(readme), 0o644); err != nil {
				return err
			}

			fmt.Printf("✓ Created %s/\n", name)
			fmt.Println("    index.md")
			fmt.Println("    .gitignore")
			fmt.Println("    README.md")
			fmt.Println("→ Add sources with `distill add` and run `distill <name>` to start compacting.")
			return nil
		},
	}
}
